package enums;

public enum StatisticData {
  NUM_OF_COMMITS, NUM_OF_DEVELOPERS, NUM_OF_RELEASES,

  NUM_OF_OPENING_ISSUES, NUM_OF_CLOSED_ISSUES, NUM_OF_PULL_REQUESTS,

  ISSUE_AVERAGE_OPEN_TIME_IN_SECOND, ISSUE_MIN_OPEN_TIME_IN_SECOND,

  ISSUE_AVERAGE_MERGING_TIME_IN_SECOND, ISSUE_MIN_MERGING_TIME_IN_SECOND
}
